### ISSUE TITLE
AUR package is not rebuild after shared lib deps change

### ISSUE THREAD

**Issue by ee9b590be72a7469e34d35705fb7c598** [oshazard/apacman#83]
Even after `apacman -Syu` one of my AUR packages does not start (after a system update) because of shared libs that do not exist anymore:

    $ sudo pacman -Syu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
    :: Starting full system upgrade...
     there is nothing to do
    $ apacman -Syu    
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
    :: Starting full system upgrade...
     there is nothing to do
    :: Synchronizing aur database...
     aur                                                    22  22 [##################################] 100%
    :: Starting full aur upgrade...
     local database is up to date
    $ mu
    mu: error while loading shared libraries: libxapian.so.22: cannot open shared object file: No such file or directory
    $ 

Just `apacman -S mu` does not help, as it simply reinstalls from cache. I had to manually reinstall with `--skipcache`.

I would expect `apacman -Syu` to take care of this. It should never just successfully finish and leave the system in a state where installed packages are not able to run.

**Comment by ee9b590be72a7469e34d35705fb7c598** [comment]
Also, it seems that a python upgrade went by unnoticed:



    $ ./index.py                    
    Traceback (most recent call last):
    File "./index.py", line 20, in <module>
    import util
    File "util.py", line 35, in <module>
    from cachecontrol import CacheControl
    ModuleNotFoundError: No module named 'cachecontrol'
    $ apacman cachecontrol
    
    0 aur/python-cachecontrol 0.11.6-1 [installed] (0)
    Python library for reading and writing bzip2-compressed files
    
    Type numbers to install. Separate each number with a space.
    Numbers: 0
    warning: python-cachecontrol-0.11.6-1 is up to date -- reinstalling
    
    Aur Targets    (1): python-cachecontrol
    
    :: Proceed with installation? [Y/n] 
    
    notice: installing python-cachecontrol-0.11.6-1 from cache
    loading packages...
    warning: python-cachecontrol-0.11.6-1 is up to date -- reinstalling
    resolving dependencies...
    looking for conflicting packages...
    
    Packages (1) python-cachecontrol-0.11.6-1
    
    Total Installed Size:  0.07 MiB
    Net Upgrade Size:      0.00 MiB
    
    :: Proceed with installation? [Y/n] 
    :: Processing package changes...
    (1/1) reinstalling python-cachecontrol                                                     
    $ ./index.py                       
    Traceback (most recent call last):
    File "./index.py", line 20, in <module>
    import util
    File "util.py", line 35, in <module>
    from cachecontrol import CacheControl
    ModuleNotFoundError: No module named 'cachecontrol'
    $ which python
    /usr/bin/python
    $ python --version
    Python 3.6.0
    $ pacman -Ql python-cachecontrol 
    python-cachecontrol /usr/
    python-cachecontrol /usr/bin/
    python-cachecontrol /usr/bin/doesitcache
    python-cachecontrol /usr/lib/
    python-cachecontrol /usr/lib/python3.5/
    python-cachecontrol /usr/lib/python3.5/site-packages/
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/PKG-INFO
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/SOURCES.txt
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/dependency_links.txt
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/entry_points.txt
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/requires.txt
    python-cachecontrol /usr/lib/python3.5/site-packages/CacheControl-0.11.6-py3.5.egg-info/top_level.txt
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__init__.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/__init__.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/_cmd.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/adapter.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/cache.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/compat.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/controller.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/filewrapper.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/heuristics.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/serialize.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/__pycache__/wrapper.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/_cmd.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/adapter.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/cache.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/__init__.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/__pycache__/
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/__pycache__/__init__.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/__pycache__/file_cache.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/__pycache__/redis_cache.cpython-35.pyc
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/file_cache.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/caches/redis_cache.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/compat.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/controller.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/filewrapper.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/heuristics.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/serialize.py
    python-cachecontrol /usr/lib/python3.5/site-packages/cachecontrol/wrapper.py
    $

This feels just... wrong.

**Comment by SolarAquarion** [comment]
You need to do the rebuild yourself
